version: 2.1


orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps :
      - checkout
      - run : mvn test
      - run : mvn validate
      - store_artifacts:
          path: target
      - codecov/upload
  docs-build:
    docker:
      - image
    steps:
      - checkout
      - run : mvn
      - store_artifacts:
          path: target/site/apidocs
  docs-deploy:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps:
      - checkout
      - attach_workspace:
          at: target/site/apidocs/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "maxime.jullien2@alumni.univ-avignon.fr"
            git config user.name "Maxime Jullien"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs/_build/html

workflows:
  build_and_test:
    jobs:
      - test:
        filters:
          branches:
            only:
              - master
      - docs-build:
          requires:
            -test
            filters:
              branches:
                only:
                  - master
      - doc-deploy:
          requires:
            - test
            - docs-build
            filters:
              branches:
                only: master

