version: 2.1


orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps :
      - checkout
      - run : mvn test
      - run : mvn validate
      - store_artifacts:
          path: target
      - codecov/upload

  docs-build:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps:
      - checkout
      - run : mvn site
      - store_artifacts:
          path: target/site/apidocs
      - persist_to_workspace:
          root: target/site
          paths: apidocs


workflows:
  build_and_test:
    jobs:
      - test
      - docs-build:
          requires:
            - test