version: 2.1


orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps :
      - checkout
      - run : mvn test
      - run : mvn validate
      - store_artifacts:
          path: target
      - codecov/upload

  docs-build:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps:
      - checkout
      - run : mvn site
      - store_artifacts:
          path: target/site/apidocs

  docs-deploy:
    docker:
      - image: cimg/openjdk:21.0.2-node
        environment:
          NODE_OPTIONS=--max-old-space-size=4096
    resource_class: large
    steps:
      - checkout
      - attach_workspace:
          at: target/site/apidocs/
      - run:
          name: Install and configure dependencies
          command: |
            npm install need sudo
            git config user.email "test@alumni.univ-avignon.fr"
            git config user.name "jullien"
            npm install --silent gh-pages
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist target/site/apidocs
      - add_ssh_keys:
          fingerprints:
            - "SHA256:RxLdmVa5e/ry0ejzLnkxDaqmKkUuK/+WNUK4kr/b04Q"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist target/site/apidocs/
workflows:
  build_and_test:
    jobs:
      - test
      - docs-build:
          requires:
            - test
      - docs-deploy:
          requires:
            - test
            - docs-build