version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run: java --version
  test:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps :
      - checkout
      - run : mvn test


workflows:
  build_and_test:
    jobs:
      - build
      - test
    filters:
      branches:
        only:
          - master