version: 2.1

jobs:
  upload-to-codecov:
    docker:
      - image: cimg/openjdk:21.0.2-node
      steps:
        - checkout
        - codecov/upload
  test:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps :
      - checkout
      - run : mvn test

orbs:
  codecov: codecov/codecov@4.0.1
workflows:
  build_and_test:
    jobs:
      - test:
        filters:
          branches:
            only:
              - master
  upload:
    jobs:
      - upload-to-codecov