version: 2.1


orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps :
      - checkout
      - run : mvn clean site
      - run : mvn clean verify
      - run : mvn test jacoco:report@default-report.
      - store_artifacts:
          path: target
      - store_artifacts:
          path: target/generated-classes/jacoco
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/
      - codecov/upload

workflows:
  build_and_test:
    jobs:
      - test:
        filters:
          branches:
            only:
              - master
